openapi: 3.0.0
info:
  title: ClassDojo API docs
  version: 1.0.0
paths:
  "/getlinks":
    post:
      summary: get s3 bucket link
      description: Get a signed link generated by s3 bucket to allow for direct image upload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/S3Links"

      responses:
        '200':
          description: Generated links for images
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/S3LinksResponse"
  "/analyze":
    post:
      summary: analyze video frames
      description: Get rekognition data analysis for images uploaded to s3 bucket related to a specific video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/dataAnalysis"

      responses:
        '200':
          description: Analyzed data
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/dataAnalysisResponse"

  "/analyze/{videoId}":
    get:
      summary: get analysis from old video
      description: Get analysis record related to a specific video
      parameters:
        - in: path
          name: videoId
          schema:
            type: string
          required: true
          description: uuid of the video data to get

      responses:
        '200':
          description: Analysis record
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/analysisRecordResponse"

components:
  schemas:
    S3LinksResponse:
      properties:
        links:
          type: array
      required:
        - links
      example:
        links: [
          'http://localhost:9000/images/testVideo/image1.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=root%2F20220516%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20220516T183211Z&X-Amz-Expires=100000&X-Amz-Signature=7fe772705878ac4178a56856f3052c35f17bb27f7c5ae4ba01a0e4f81785368e&X-Amz-SignedHeaders=host',
          'http://localhost:9000/images/testVideo/image2.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=root%2F20220516%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20220516T183211Z&X-Amz-Expires=100000&X-Amz-Signature=313f68d1a0eb33b9d2265f771944b30468ff0a2e2d0fd36ba64119f988f05a07&X-Amz-SignedHeaders=host',
          'http://localhost:9000/images/testVideo/image3.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=root%2F20220516%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20220516T183211Z&X-Amz-Expires=100000&X-Amz-Signature=baf1d5393d6314aa7e81049adc760e57c345ba47d2be1804d1110dce32622ad6&X-Amz-SignedHeaders=host',
        ]


    S3Links:
      properties:
        videoId:
          type: string
        frames:
          type: array
      required:
        - videoId
        - frames
      example:
        videoId: testVideo
        frames: [ testVideo/1.jpg, testVideo/2.jpg ]

    dataAnalysis:
      properties:
        videoId:
          type: string
      required:
        - videoId
      example:
        videoId: testVideo

    dataAnalysisResponse:
      properties:
        framesArray:
          type: array
          items:
            type: object
            properties:
              attentionScore:
                type: number
              moodScore:
                type: number
              amountOfPeople:
                type: number
              isImportantAttention:
                type: boolean
              isImportantMood:
                type: boolean
              isImportantPeople:
                type: boolean
              facesDetail:
                type: array
                items:
                  type: object
                  properties:
                    boundingBox:
                      type: object
                      properties:
                        Width:
                          type: number
                        Height:
                          type: number
                        Left:
                          type: number
                        Top:
                          type: number
                    topEmotion:
                      type: object
                      properties:
                        Type:
                          type: string
                        Confidence:
                          type: number

          example:
            - attentionScore: 0.65
              moodScore: 0.39
              amountOfPeople: 19
              facesDetail:
                - boundingBox:
                    Width: 0.12799087166786194
                    Height: 0.31783920526504517
                    Left: 0.6253703832626343
                    Top: 0.08763377368450165
                  topEmotion:
                    Type: CONFUSED
                    Confidence: 99.63795471191406
                - boundingBox:
                    Width: 0.09457354992628098
                    Height: 0.22096648812294006
                    Left: 0.17085716128349304
                    Top: 0.6672175526618958
                  topEmotion:
                    Type: CALM
                    Confidence: 96.443603515625
                - boundingBox:
                    Width: 0.0846099704504013
                    Height: 0.19836215674877167
                    Left: 0.20270614326000214
                    Top: 0.16728106141090393
                    topEmotion:
                      Type: CALM
                      Confidence: 77.0023193359375
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: true
            - attentionScore: 0.6
              moodScore: 0.4
              amountOfPeople: 19
              facesDetail:
                - boundingBox:
                    Width: 0.13665208220481873
                    Height: 0.27526575326919556
                    Left: 0.198362797498703
                    Top: 0.7325266599655151
                  topEmotion:
                    Type: SAD
                    Confidence: 98.96540069580078
                - boundingBox:
                    Width: 0.09949468821287155
                    Height: 0.24421581625938416
                    Left: 0.24007287621498108
                    Top: 0.12005813419818878
                  topEmotion:
                    Type: CALM
                    Confidence: 99.75934600830078
                - boundingBox:
                    Width: 0.07053308933973312
                    Height: 0.16228044033050537
                    Left: 0.7046615481376648
                    Top: 0.6824442744255066
                    topEmotion:
                      Type: CALM
                      Confidence: 71.59647369384766
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.89
              moodScore: 0.22
              amountOfPeople: 19
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: false
            - attentionScore: 0.46
              moodScore: 0.36
              amountOfPeople: 18
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: true
            - attentionScore: 0.54
              moodScore: 0.38
              amountOfPeople: 18
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.51
              moodScore: 0.35
              amountOfPeople: 18
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.48
              moodScore: 0.33
              amountOfPeople: 18
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.56
              moodScore: 0.4
              amountOfPeople: 17
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: true
            - attentionScore: 0.78
              moodScore: 0.87
              amountOfPeople: 18
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: true
            - attentionScore: 0.46
              moodScore: 0.29
              amountOfPeople: 16
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: true
            - attentionScore: 0.53
              moodScore: 0.33
              amountOfPeople: 16
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.29
              moodScore: 0.18
              amountOfPeople: 16
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: false
            - attentionScore: 0.55
              moodScore: 0.31
              amountOfPeople: 16
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.55
              moodScore: 0.46
              amountOfPeople: 16
              isImportantAttention: false
              isImportantMood: true
              isImportantPeople: false
            - attentionScore: 0.10
              moodScore: 0.30
              amountOfPeople: 15
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: true
        peaks:
          type: object
          properties:
            moodPeak:
              type: number
            attentionPeak:
              type: number
            peoplePeak:
              type: number
          example:
            moodPeak: 0.46
            attentionPeak: 0.89
            peoplePeak: 19
        valleys:
          type: object
          properties:
            moodValley:
              type: number
            attentionValley:
              type: number
            peopleValley:
              type: number
          example:
            moodValley: 0.18
            attentionValley: 0.10
            peopleValley: 15
        averages:
          type: object
          properties:
            moodAverage:
              type: number
            attentionAverage:
              type: number
            peopleAverage:
              type: number
          example:
            moodAverage: 0.37
            attentionAverage: 0.55
            peopleAverage: 17
      required:
        - framesArray
        - peaks
        - valleys
        - averages

    analysisRecordResponse:
      properties:
        framesArray:
          type: array
          items:
            type: object
            properties:
              attentionScore:
                type: number
              moodScore:
                type: number
              amountOfPeople:
                type: number
              isImportantAttention:
                type: boolean
              isImportantMood:
                type: boolean
              isImportantPeople:
                type: boolean
          example:
            - attentionScore: 0.65
              moodScore: 0.39
              amountOfPeople: 19
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: true
            - attentionScore: 0.6
              moodScore: 0.4
              amountOfPeople: 19
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.89
              moodScore: 0.22
              amountOfPeople: 19
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: false
            - attentionScore: 0.46
              moodScore: 0.36
              amountOfPeople: 18
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: true
            - attentionScore: 0.54
              moodScore: 0.38
              amountOfPeople: 18
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.51
              moodScore: 0.35
              amountOfPeople: 18
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.48
              moodScore: 0.33
              amountOfPeople: 18
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.56
              moodScore: 0.4
              amountOfPeople: 17
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: true
            - attentionScore: 0.78
              moodScore: 0.87
              amountOfPeople: 18
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: true
            - attentionScore: 0.46
              moodScore: 0.29
              amountOfPeople: 16
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: true
            - attentionScore: 0.53
              moodScore: 0.33
              amountOfPeople: 16
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.29
              moodScore: 0.18
              amountOfPeople: 16
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: false
            - attentionScore: 0.55
              moodScore: 0.31
              amountOfPeople: 16
              isImportantAttention: false
              isImportantMood: false
              isImportantPeople: false
            - attentionScore: 0.55
              moodScore: 0.46
              amountOfPeople: 16
              isImportantAttention: false
              isImportantMood: true
              isImportantPeople: false
            - attentionScore: 0.10
              moodScore: 0.30
              amountOfPeople: 15
              isImportantAttention: true
              isImportantMood: true
              isImportantPeople: true
        peaks:
          type: object
          properties:
            moodPeak:
              type: number
            attentionPeak:
              type: number
            peoplePeak:
              type: number
          example:
            moodPeak: 0.46
            attentionPeak: 0.89
            peoplePeak: 19
        valleys:
          type: object
          properties:
            moodValley:
              type: number
            attentionValley:
              type: number
            peopleValley:
              type: number
          example:
            moodValley: 0.18
            attentionValley: 0.10
            peopleValley: 15
        averages:
          type: object
          properties:
            moodAverage:
              type: number
            attentionAverage:
              type: number
            peopleAverage:
              type: number
          example:
            moodAverage: 0.37
            attentionAverage: 0.55
            peopleAverage: 17
        videoName:
          type: string
          example: "sample chunk"
        videoDate:
          type: string
          example: "2022-05-07T13:35:38.467Z"
        duration:
          type: number
          example: 76
        accuracy:
          type: number
          example: 5
      required:
        - framesArray
        - peaks
        - valleys
        - averages
        - videoName
        - videoDate
        - duration
        - accuracy
